"""Storage backend helpers for Hermes control-plane state."""

from __future__ import annotations

from contextlib import contextmanager
from pathlib import Path
from typing import Any, Iterator
import json
import os
import sys


RUNTIME_ENV_NAME = "runtime.env"
DEFAULT_BACKEND = "file"
DEFAULT_DATABASE_URL = "postgresql:///hermes_control"
MIGRATION_META_KEY = "file_migration_v1"
MEMORY_MIGRATION_META_KEY = "agent_memory_seed_v1"


def repo_root(root_dir: str | Path | None = None) -> Path:
    if root_dir is not None:
        return Path(root_dir).resolve()
    return Path(__file__).resolve().parents[1]


def hermes_state_dir(root_dir: str | Path | None = None) -> Path:
    return repo_root(root_dir) / "state" / "hermes"


def runtime_env_path(root_dir: str | Path | None = None) -> Path:
    return hermes_state_dir(root_dir) / RUNTIME_ENV_NAME


def _read_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def _write_env_file(path: Path, mapping: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by Hermes state storage", ""]
    for key in sorted(mapping):
        lines.append(f"{key}={mapping[key]}")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def runtime_settings(root_dir: str | Path | None = None) -> dict[str, str]:
    root = repo_root(root_dir)
    file_values = _read_env_file(runtime_env_path(root))
    backend = os.environ.get("HERMES_STATE_BACKEND", file_values.get("HERMES_STATE_BACKEND", DEFAULT_BACKEND)).strip().lower() or DEFAULT_BACKEND
    database_url = os.environ.get("HERMES_DATABASE_URL", file_values.get("HERMES_DATABASE_URL", "")).strip()
    return {
        "backend": backend,
        "database_url": database_url or (DEFAULT_DATABASE_URL if backend == "postgres" else ""),
    }


def state_backend(root_dir: str | Path | None = None) -> str:
    return runtime_settings(root_dir).get("backend", DEFAULT_BACKEND)


def database_url(root_dir: str | Path | None = None) -> str:
    return runtime_settings(root_dir).get("database_url", "")


def configure_runtime(
    root_dir: str | Path | None = None,
    *,
    backend: str,
    database_url_value: str = "",
) -> dict[str, str]:
    root = repo_root(root_dir)
    normalized_backend = (backend or DEFAULT_BACKEND).strip().lower() or DEFAULT_BACKEND
    payload = {
        "HERMES_STATE_BACKEND": normalized_backend,
    }
    if normalized_backend == "postgres":
        payload["HERMES_DATABASE_URL"] = database_url_value.strip() or DEFAULT_DATABASE_URL
    else:
        payload["HERMES_DATABASE_URL"] = ""
    _write_env_file(runtime_env_path(root), payload)
    return runtime_settings(root)


def using_postgres(root_dir: str | Path | None = None) -> bool:
    return state_backend(root_dir) == "postgres" and bool(database_url(root_dir))


def _ensure_psycopg_importable(root_dir: Path) -> None:
    try:
        import psycopg  # noqa: F401
        return
    except ImportError:
        pass

    site_packages = sorted((root_dir / "state" / "hermes" / "venv").glob("lib/python*/site-packages"))
    for path in site_packages:
        if str(path) not in sys.path:
            sys.path.insert(0, str(path))


def _load_json_value(value: object) -> dict[str, Any]:
    if isinstance(value, dict):
        return value
    if isinstance(value, str):
        try:
            loaded = json.loads(value)
        except json.JSONDecodeError:
            return {}
        return loaded if isinstance(loaded, dict) else {}
    return {}


@contextmanager
def _connect(root_dir: str | Path | None = None) -> Iterator[Any]:
    root = repo_root(root_dir)
    _ensure_psycopg_importable(root)
    import psycopg

    conn = psycopg.connect(database_url(root), autocommit=True)
    try:
        yield conn
    finally:
        conn.close()


def ensure_postgres_ready(root_dir: str | Path | None = None) -> None:
    if not using_postgres(root_dir):
        return
    root = repo_root(root_dir)

    with _connect(root) as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS hermes_meta (
                    key TEXT PRIMARY KEY,
                    value JSONB NOT NULL DEFAULT '{}'::jsonb,
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );

                CREATE TABLE IF NOT EXISTS hermes_projects (
                    project_id TEXT PRIMARY KEY,
                    root_path TEXT NOT NULL,
                    payload JSONB NOT NULL,
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );

                CREATE TABLE IF NOT EXISTS hermes_portfolio (
                    portfolio_key TEXT PRIMARY KEY,
                    payload JSONB NOT NULL,
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );

                CREATE TABLE IF NOT EXISTS hermes_portal_runs (
                    run_id TEXT PRIMARY KEY,
                    project_id TEXT NOT NULL DEFAULT '',
                    payload JSONB NOT NULL,
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );

                CREATE TABLE IF NOT EXISTS hermes_specialist_dispatches (
                    dispatch_id TEXT PRIMARY KEY,
                    project_id TEXT NOT NULL DEFAULT '',
                    profile TEXT NOT NULL DEFAULT '',
                    slice_key TEXT NOT NULL DEFAULT '',
                    status TEXT NOT NULL DEFAULT '',
                    payload JSONB NOT NULL,
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );

                CREATE INDEX IF NOT EXISTS hermes_projects_updated_at_idx
                    ON hermes_projects (updated_at DESC);

                CREATE INDEX IF NOT EXISTS hermes_portal_runs_project_idx
                    ON hermes_portal_runs (project_id, updated_at DESC);

                CREATE INDEX IF NOT EXISTS hermes_dispatches_project_idx
                    ON hermes_specialist_dispatches (project_id, updated_at DESC);

                CREATE TABLE IF NOT EXISTS hermes_agents (
                    agent_slug TEXT PRIMARY KEY,
                    profile_key TEXT NOT NULL,
                    lane TEXT NOT NULL,
                    character_name TEXT NOT NULL,
                    payload JSONB NOT NULL,
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );

                CREATE TABLE IF NOT EXISTS hermes_memory_nodes (
                    node_id TEXT PRIMARY KEY,
                    agent_slug TEXT NOT NULL,
                    scope TEXT NOT NULL,
                    kind TEXT NOT NULL,
                    title TEXT NOT NULL,
                    content TEXT NOT NULL,
                    source_path TEXT NOT NULL DEFAULT '',
                    confidence DOUBLE PRECISION NOT NULL DEFAULT 1.0,
                    weight DOUBLE PRECISION NOT NULL DEFAULT 1.0,
                    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );

                CREATE TABLE IF NOT EXISTS hermes_memory_synapses (
                    edge_id TEXT PRIMARY KEY,
                    agent_slug TEXT NOT NULL,
                    from_node_id TEXT NOT NULL,
                    to_node_id TEXT NOT NULL,
                    relation TEXT NOT NULL,
                    weight DOUBLE PRECISION NOT NULL DEFAULT 1.0,
                    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );

                CREATE INDEX IF NOT EXISTS hermes_memory_nodes_agent_idx
                    ON hermes_memory_nodes (agent_slug, kind, updated_at DESC);

                CREATE INDEX IF NOT EXISTS hermes_memory_synapses_agent_idx
                    ON hermes_memory_synapses (agent_slug, relation, weight DESC);

                CREATE TABLE IF NOT EXISTS hermes_cognitive_events (
                    event_id TEXT PRIMARY KEY,
                    agent_slug TEXT NOT NULL DEFAULT '',
                    project_id TEXT NOT NULL DEFAULT '',
                    event_type TEXT NOT NULL,
                    title TEXT NOT NULL,
                    content TEXT NOT NULL,
                    source_ref TEXT NOT NULL DEFAULT '',
                    salience DOUBLE PRECISION NOT NULL DEFAULT 0.5,
                    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
                    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );

                CREATE TABLE IF NOT EXISTS hermes_cognitive_facts (
                    fact_id TEXT PRIMARY KEY,
                    scope TEXT NOT NULL,
                    subject TEXT NOT NULL,
                    predicate TEXT NOT NULL,
                    object TEXT NOT NULL,
                    confidence DOUBLE PRECISION NOT NULL DEFAULT 0.75,
                    source_event_id TEXT NOT NULL DEFAULT '',
                    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );

                CREATE TABLE IF NOT EXISTS hermes_cognitive_procedures (
                    procedure_id TEXT PRIMARY KEY,
                    agent_slug TEXT NOT NULL,
                    trigger TEXT NOT NULL,
                    title TEXT NOT NULL,
                    steps JSONB NOT NULL DEFAULT '[]'::jsonb,
                    confidence DOUBLE PRECISION NOT NULL DEFAULT 0.75,
                    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );

                CREATE TABLE IF NOT EXISTS hermes_cognitive_reflections (
                    reflection_id TEXT PRIMARY KEY,
                    agent_slug TEXT NOT NULL,
                    project_id TEXT NOT NULL DEFAULT '',
                    title TEXT NOT NULL,
                    content TEXT NOT NULL,
                    lessons JSONB NOT NULL DEFAULT '[]'::jsonb,
                    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );

                CREATE TABLE IF NOT EXISTS hermes_cognitive_activations (
                    activation_id TEXT PRIMARY KEY,
                    query TEXT NOT NULL,
                    agent_slug TEXT NOT NULL DEFAULT '',
                    project_id TEXT NOT NULL DEFAULT '',
                    activated_nodes JSONB NOT NULL DEFAULT '[]'::jsonb,
                    activated_facts JSONB NOT NULL DEFAULT '[]'::jsonb,
                    activated_procedures JSONB NOT NULL DEFAULT '[]'::jsonb,
                    chosen_action TEXT NOT NULL DEFAULT '',
                    confidence DOUBLE PRECISION NOT NULL DEFAULT 0.0,
                    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );

                CREATE TABLE IF NOT EXISTS hermes_agent_beliefs (
                    belief_id TEXT PRIMARY KEY,
                    agent_slug TEXT NOT NULL,
                    subject TEXT NOT NULL,
                    belief TEXT NOT NULL,
                    confidence DOUBLE PRECISION NOT NULL DEFAULT 0.75,
                    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );

                CREATE TABLE IF NOT EXISTS hermes_cognitive_contradictions (
                    contradiction_id TEXT PRIMARY KEY,
                    scope TEXT NOT NULL,
                    subject TEXT NOT NULL,
                    statement_a TEXT NOT NULL,
                    statement_b TEXT NOT NULL,
                    status TEXT NOT NULL DEFAULT 'open',
                    severity DOUBLE PRECISION NOT NULL DEFAULT 0.5,
                    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );

                CREATE TABLE IF NOT EXISTS hermes_dream_jobs (
                    job_id TEXT PRIMARY KEY,
                    agent_slug TEXT NOT NULL,
                    job_type TEXT NOT NULL,
                    status TEXT NOT NULL DEFAULT 'queued',
                    objective TEXT NOT NULL,
                    result JSONB NOT NULL DEFAULT '{}'::jsonb,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );

                CREATE TABLE IF NOT EXISTS hermes_council_records (
                    council_id TEXT PRIMARY KEY,
                    project_id TEXT NOT NULL DEFAULT '',
                    topic TEXT NOT NULL,
                    positions JSONB NOT NULL DEFAULT '[]'::jsonb,
                    decision TEXT NOT NULL,
                    confidence DOUBLE PRECISION NOT NULL DEFAULT 0.0,
                    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );

                CREATE TABLE IF NOT EXISTS hermes_experiments (
                    experiment_id TEXT PRIMARY KEY,
                    project_id TEXT NOT NULL DEFAULT '',
                    hypothesis TEXT NOT NULL,
                    metric TEXT NOT NULL,
                    status TEXT NOT NULL DEFAULT 'proposed',
                    risk TEXT NOT NULL DEFAULT 'medium',
                    confidence DOUBLE PRECISION NOT NULL DEFAULT 0.0,
                    result JSONB NOT NULL DEFAULT '{}'::jsonb,
                    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );

                CREATE TABLE IF NOT EXISTS hermes_skill_evolutions (
                    evolution_id TEXT PRIMARY KEY,
                    agent_slug TEXT NOT NULL,
                    skill_area TEXT NOT NULL,
                    evidence TEXT NOT NULL,
                    recommendation TEXT NOT NULL,
                    confidence DOUBLE PRECISION NOT NULL DEFAULT 0.0,
                    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );

                CREATE TABLE IF NOT EXISTS hermes_autonomy_decisions (
                    decision_id TEXT PRIMARY KEY,
                    project_id TEXT NOT NULL DEFAULT '',
                    objective TEXT NOT NULL,
                    risk TEXT NOT NULL DEFAULT 'medium',
                    confidence DOUBLE PRECISION NOT NULL DEFAULT 0.0,
                    decision TEXT NOT NULL,
                    reasons JSONB NOT NULL DEFAULT '[]'::jsonb,
                    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );

                CREATE TABLE IF NOT EXISTS hermes_agent_heartbeats (
                    heartbeat_id TEXT PRIMARY KEY,
                    agent_slug TEXT NOT NULL,
                    project_id TEXT NOT NULL DEFAULT '',
                    status TEXT NOT NULL DEFAULT 'listening',
                    observation TEXT NOT NULL,
                    intention TEXT NOT NULL,
                    confidence DOUBLE PRECISION NOT NULL DEFAULT 0.0,
                    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );

                CREATE TABLE IF NOT EXISTS hermes_agent_intentions (
                    intention_id TEXT PRIMARY KEY,
                    agent_slug TEXT NOT NULL,
                    project_id TEXT NOT NULL DEFAULT '',
                    title TEXT NOT NULL,
                    action_type TEXT NOT NULL,
                    status TEXT NOT NULL DEFAULT 'proposed',
                    risk TEXT NOT NULL DEFAULT 'low',
                    confidence DOUBLE PRECISION NOT NULL DEFAULT 0.0,
                    autonomy_decision TEXT NOT NULL DEFAULT '',
                    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );

                CREATE INDEX IF NOT EXISTS hermes_cognitive_events_agent_idx
                    ON hermes_cognitive_events (agent_slug, event_type, occurred_at DESC);

                CREATE INDEX IF NOT EXISTS hermes_cognitive_facts_subject_idx
                    ON hermes_cognitive_facts (scope, subject, predicate);

                CREATE INDEX IF NOT EXISTS hermes_beliefs_agent_idx
                    ON hermes_agent_beliefs (agent_slug, subject, confidence DESC);

                CREATE INDEX IF NOT EXISTS hermes_contradictions_status_idx
                    ON hermes_cognitive_contradictions (status, severity DESC);

                CREATE INDEX IF NOT EXISTS hermes_experiments_status_idx
                    ON hermes_experiments (status, risk, updated_at DESC);

                CREATE INDEX IF NOT EXISTS hermes_skill_evolutions_agent_idx
                    ON hermes_skill_evolutions (agent_slug, skill_area, confidence DESC);

                CREATE INDEX IF NOT EXISTS hermes_autonomy_decisions_risk_idx
                    ON hermes_autonomy_decisions (risk, decision, updated_at DESC);

                CREATE INDEX IF NOT EXISTS hermes_agent_heartbeats_agent_idx
                    ON hermes_agent_heartbeats (agent_slug, status, updated_at DESC);

                CREATE INDEX IF NOT EXISTS hermes_agent_intentions_status_idx
                    ON hermes_agent_intentions (status, risk, updated_at DESC);
                """
            )

            cur.execute("SELECT value FROM hermes_meta WHERE key = %s", (MIGRATION_META_KEY,))
            row = cur.fetchone()
            migrated = _load_json_value(row[0]).get("completed") if row else False
            if migrated:
                return

        migrate_file_state_to_postgres(root)
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO hermes_meta (key, value, updated_at)
                VALUES (%s, %s::jsonb, NOW())
                ON CONFLICT (key) DO UPDATE
                SET value = EXCLUDED.value,
                    updated_at = NOW()
                """,
                (MIGRATION_META_KEY, json.dumps({"completed": True})),
            )


def _portal_runs_dir(root_dir: str | Path | None = None) -> Path:
    path = hermes_state_dir(root_dir) / "portal_runs"
    path.mkdir(parents=True, exist_ok=True)
    return path


def _dispatch_dir(root_dir: str | Path | None = None) -> Path:
    path = hermes_state_dir(root_dir) / "specialist_dispatches"
    path.mkdir(parents=True, exist_ok=True)
    return path


def _portfolio_path(root_dir: str | Path | None = None) -> Path:
    path = hermes_state_dir(root_dir) / "orchestration"
    path.mkdir(parents=True, exist_ok=True)
    return path / "portfolio.json"


def _project_manifest_path(root_dir: str | Path | None, project_id: str) -> Path:
    return repo_root(root_dir) / "state" / "projects" / project_id / "project.json"


def _memory_graph_path(root_dir: str | Path | None = None) -> Path:
    return hermes_state_dir(root_dir) / "memory_graph.json"


def _cognition_graph_path(root_dir: str | Path | None = None) -> Path:
    return hermes_state_dir(root_dir) / "cognitive_kernel.json"


def _write_json(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def _load_memory_graph_file(root_dir: str | Path | None = None) -> dict[str, Any]:
    path = _memory_graph_path(root_dir)
    if not path.exists():
        return {"agents": {}, "nodes": {}, "synapses": {}}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {"agents": {}, "nodes": {}, "synapses": {}}
    if not isinstance(payload, dict):
        return {"agents": {}, "nodes": {}, "synapses": {}}
    return {
        "agents": payload.get("agents") if isinstance(payload.get("agents"), dict) else {},
        "nodes": payload.get("nodes") if isinstance(payload.get("nodes"), dict) else {},
        "synapses": payload.get("synapses") if isinstance(payload.get("synapses"), dict) else {},
    }


def _save_memory_graph_file(root_dir: str | Path | None, payload: dict[str, Any]) -> None:
    _write_json(_memory_graph_path(root_dir), payload)


def _load_cognition_file(root_dir: str | Path | None = None) -> dict[str, Any]:
    path = _cognition_graph_path(root_dir)
    sections = {
        "events": {},
        "facts": {},
        "procedures": {},
        "reflections": {},
        "activations": {},
        "beliefs": {},
        "contradictions": {},
        "dream_jobs": {},
        "council_records": {},
        "experiments": {},
        "skill_evolutions": {},
        "autonomy_decisions": {},
        "agent_heartbeats": {},
        "agent_intentions": {},
    }
    if not path.exists():
        return sections
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return sections
    if not isinstance(payload, dict):
        return sections
    for key in sections:
        if isinstance(payload.get(key), dict):
            sections[key] = payload[key]
    return sections


def _save_cognition_file(root_dir: str | Path | None, payload: dict[str, Any]) -> None:
    _write_json(_cognition_graph_path(root_dir), payload)


def migrate_file_state_to_postgres(root_dir: str | Path | None = None) -> dict[str, int]:
    root = repo_root(root_dir)
    if not using_postgres(root):
        return {"projects": 0, "portfolio": 0, "portal_runs": 0, "dispatches": 0}

    counts = {"projects": 0, "portfolio": 0, "portal_runs": 0, "dispatches": 0}
    with _connect(root) as conn:
        with conn.cursor() as cur:
            project_root = root / "state" / "projects"
            if project_root.exists():
                for manifest_path in sorted(project_root.glob("*/project.json")):
                    try:
                        payload = json.loads(manifest_path.read_text(encoding="utf-8"))
                    except (OSError, json.JSONDecodeError):
                        continue
                    cur.execute(
                        """
                        INSERT INTO hermes_projects (project_id, root_path, payload, updated_at)
                        VALUES (%s, %s, %s::jsonb, NOW())
                        ON CONFLICT (project_id) DO UPDATE
                        SET root_path = EXCLUDED.root_path,
                            payload = EXCLUDED.payload,
                            updated_at = NOW()
                        """,
                        (
                            str(payload.get("project_id") or manifest_path.parent.name).strip().lower(),
                            str(manifest_path.parent.resolve()),
                            json.dumps(payload),
                        ),
                    )
                    counts["projects"] += 1

            portfolio_path = _portfolio_path(root)
            if portfolio_path.exists():
                try:
                    payload = json.loads(portfolio_path.read_text(encoding="utf-8"))
                except (OSError, json.JSONDecodeError):
                    payload = None
                if isinstance(payload, dict):
                    cur.execute(
                        """
                        INSERT INTO hermes_portfolio (portfolio_key, payload, updated_at)
                        VALUES ('default', %s::jsonb, NOW())
                        ON CONFLICT (portfolio_key) DO UPDATE
                        SET payload = EXCLUDED.payload,
                            updated_at = NOW()
                        """,
                        (json.dumps(payload),),
                    )
                    counts["portfolio"] += 1

            for path in sorted(_portal_runs_dir(root).glob("*.json")):
                try:
                    payload = json.loads(path.read_text(encoding="utf-8"))
                except (OSError, json.JSONDecodeError):
                    continue
                if isinstance(payload, dict):
                    cur.execute(
                        """
                        INSERT INTO hermes_portal_runs (run_id, project_id, payload, updated_at)
                        VALUES (%s, %s, %s::jsonb, NOW())
                        ON CONFLICT (run_id) DO UPDATE
                        SET project_id = EXCLUDED.project_id,
                            payload = EXCLUDED.payload,
                            updated_at = NOW()
                        """,
                        (
                            str(payload.get("run_id") or path.stem).strip(),
                            str(payload.get("project_id") or "").strip(),
                            json.dumps(payload),
                        ),
                    )
                    counts["portal_runs"] += 1

            for path in sorted(_dispatch_dir(root).glob("*.json")):
                try:
                    payload = json.loads(path.read_text(encoding="utf-8"))
                except (OSError, json.JSONDecodeError):
                    continue
                if isinstance(payload, dict):
                    cur.execute(
                        """
                        INSERT INTO hermes_specialist_dispatches (dispatch_id, project_id, profile, slice_key, status, payload, updated_at)
                        VALUES (%s, %s, %s, %s, %s, %s::jsonb, NOW())
                        ON CONFLICT (dispatch_id) DO UPDATE
                        SET project_id = EXCLUDED.project_id,
                            profile = EXCLUDED.profile,
                            slice_key = EXCLUDED.slice_key,
                            status = EXCLUDED.status,
                            payload = EXCLUDED.payload,
                            updated_at = NOW()
                        """,
                        (
                            str(payload.get("dispatch_id") or path.stem).strip(),
                            str(payload.get("project_id") or "").strip(),
                            str(payload.get("profile") or "").strip(),
                            str(payload.get("slice_key") or "").strip(),
                            str(payload.get("status") or "").strip(),
                            json.dumps(payload),
                        ),
                    )
                    counts["dispatches"] += 1

    return counts


def list_project_entries(root_dir: str | Path | None = None) -> list[tuple[Path, dict[str, Any]]]:
    root = repo_root(root_dir)
    if not using_postgres(root):
        rows: list[tuple[Path, dict[str, Any]]] = []
        for manifest_path in sorted((root / "state" / "projects").glob("*/project.json")):
            try:
                payload = json.loads(manifest_path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                continue
            rows.append((manifest_path.parent, payload))
        return rows

    ensure_postgres_ready(root)
    with _connect(root) as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT root_path, payload
                FROM hermes_projects
                ORDER BY project_id
                """
            )
            return [(Path(str(row[0])).resolve(), _load_json_value(row[1])) for row in cur.fetchall()]


def load_project_entry(root_dir: str | Path | None, project_id: str) -> tuple[Path, dict[str, Any]] | None:
    root = repo_root(root_dir)
    normalized_id = str(project_id or "").strip().lower()
    if not normalized_id:
        return None
    if not using_postgres(root):
        path = _project_manifest_path(root, normalized_id)
        if not path.exists():
            return None
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return None
        return path.parent, payload

    ensure_postgres_ready(root)
    with _connect(root) as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT root_path, payload
                FROM hermes_projects
                WHERE project_id = %s
                """,
                (normalized_id,),
            )
            row = cur.fetchone()
            if row is None:
                return None
            return Path(str(row[0])).resolve(), _load_json_value(row[1])


def save_project_payload(root_dir: str | Path | None, project_root: Path, payload: dict[str, Any]) -> dict[str, Any]:
    root = repo_root(root_dir)
    normalized_id = str(payload.get("project_id") or "").strip().lower()
    if not using_postgres(root):
        _write_json(project_root / "project.json", payload)
        return payload

    ensure_postgres_ready(root)
    with _connect(root) as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO hermes_projects (project_id, root_path, payload, updated_at)
                VALUES (%s, %s, %s::jsonb, NOW())
                ON CONFLICT (project_id) DO UPDATE
                SET root_path = EXCLUDED.root_path,
                    payload = EXCLUDED.payload,
                    updated_at = NOW()
                """,
                (normalized_id, str(project_root.resolve()), json.dumps(payload)),
            )
    return payload


def load_portfolio_payload(root_dir: str | Path | None = None) -> dict[str, Any] | None:
    root = repo_root(root_dir)
    if not using_postgres(root):
        path = _portfolio_path(root)
        if not path.exists():
            return None
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return None
        return payload if isinstance(payload, dict) else None

    ensure_postgres_ready(root)
    with _connect(root) as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT payload
                FROM hermes_portfolio
                WHERE portfolio_key = 'default'
                """
            )
            row = cur.fetchone()
            if row is None:
                return None
            return _load_json_value(row[0])


def save_portfolio_payload(root_dir: str | Path | None, payload: dict[str, Any]) -> dict[str, Any]:
    root = repo_root(root_dir)
    if not using_postgres(root):
        _write_json(_portfolio_path(root), payload)
        return payload

    ensure_postgres_ready(root)
    with _connect(root) as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO hermes_portfolio (portfolio_key, payload, updated_at)
                VALUES ('default', %s::jsonb, NOW())
                ON CONFLICT (portfolio_key) DO UPDATE
                SET payload = EXCLUDED.payload,
                    updated_at = NOW()
                """,
                (json.dumps(payload),),
            )
    return payload


def load_portal_run(root_dir: str | Path | None, run_id: str) -> dict[str, Any] | None:
    root = repo_root(root_dir)
    normalized_id = str(run_id or "").strip()
    if not normalized_id:
        return None
    if not using_postgres(root):
        path = _portal_runs_dir(root) / f"{normalized_id}.json"
        if not path.exists():
            return None
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return None
        return payload if isinstance(payload, dict) else None

    ensure_postgres_ready(root)
    with _connect(root) as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT payload
                FROM hermes_portal_runs
                WHERE run_id = %s
                """,
                (normalized_id,),
            )
            row = cur.fetchone()
            if row is None:
                return None
            return _load_json_value(row[0])


def list_portal_runs(root_dir: str | Path | None = None) -> list[dict[str, Any]]:
    root = repo_root(root_dir)
    if not using_postgres(root):
        rows: list[dict[str, Any]] = []
        for path in _portal_runs_dir(root).glob("*.json"):
            try:
                payload = json.loads(path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                continue
            if isinstance(payload, dict):
                rows.append(payload)
        rows.sort(key=lambda item: str(item.get("created_at") or ""), reverse=True)
        return rows

    ensure_postgres_ready(root)
    with _connect(root) as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT payload
                FROM hermes_portal_runs
                ORDER BY COALESCE(payload->>'created_at', '') DESC, run_id DESC
                """
            )
            return [_load_json_value(row[0]) for row in cur.fetchall()]


def upsert_portal_run(root_dir: str | Path | None, payload: dict[str, Any]) -> dict[str, Any]:
    root = repo_root(root_dir)
    run_id = str(payload.get("run_id") or "").strip()
    if not using_postgres(root):
        _write_json(_portal_runs_dir(root) / f"{run_id}.json", payload)
        return payload

    ensure_postgres_ready(root)
    with _connect(root) as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO hermes_portal_runs (run_id, project_id, payload, updated_at)
                VALUES (%s, %s, %s::jsonb, NOW())
                ON CONFLICT (run_id) DO UPDATE
                SET project_id = EXCLUDED.project_id,
                    payload = EXCLUDED.payload,
                    updated_at = NOW()
                """,
                (
                    run_id,
                    str(payload.get("project_id") or "").strip(),
                    json.dumps(payload),
                ),
            )
    return payload


def load_dispatch(root_dir: str | Path | None, dispatch_id: str) -> dict[str, Any] | None:
    root = repo_root(root_dir)
    normalized_id = str(dispatch_id or "").strip()
    if not normalized_id:
        return None
    if not using_postgres(root):
        path = _dispatch_dir(root) / f"{normalized_id}.json"
        if not path.exists():
            return None
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return None
        return payload if isinstance(payload, dict) else None

    ensure_postgres_ready(root)
    with _connect(root) as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT payload
                FROM hermes_specialist_dispatches
                WHERE dispatch_id = %s
                """,
                (normalized_id,),
            )
            row = cur.fetchone()
            if row is None:
                return None
            return _load_json_value(row[0])


def list_dispatches(root_dir: str | Path | None = None) -> list[dict[str, Any]]:
    root = repo_root(root_dir)
    if not using_postgres(root):
        rows: list[dict[str, Any]] = []
        for path in _dispatch_dir(root).glob("*.json"):
            try:
                payload = json.loads(path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                continue
            if isinstance(payload, dict):
                rows.append(payload)
        rows.sort(key=lambda item: str(item.get("created_at") or ""), reverse=True)
        return rows

    ensure_postgres_ready(root)
    with _connect(root) as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT payload
                FROM hermes_specialist_dispatches
                ORDER BY COALESCE(payload->>'created_at', '') DESC, dispatch_id DESC
                """
            )
            return [_load_json_value(row[0]) for row in cur.fetchall()]


def upsert_dispatch(root_dir: str | Path | None, payload: dict[str, Any]) -> dict[str, Any]:
    root = repo_root(root_dir)
    dispatch_id = str(payload.get("dispatch_id") or "").strip()
    if not using_postgres(root):
        _write_json(_dispatch_dir(root) / f"{dispatch_id}.json", payload)
        return payload

    ensure_postgres_ready(root)
    with _connect(root) as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO hermes_specialist_dispatches (dispatch_id, project_id, profile, slice_key, status, payload, updated_at)
                VALUES (%s, %s, %s, %s, %s, %s::jsonb, NOW())
                ON CONFLICT (dispatch_id) DO UPDATE
                SET project_id = EXCLUDED.project_id,
                    profile = EXCLUDED.profile,
                    slice_key = EXCLUDED.slice_key,
                    status = EXCLUDED.status,
                    payload = EXCLUDED.payload,
                    updated_at = NOW()
                """,
                (
                    dispatch_id,
                    str(payload.get("project_id") or "").strip(),
                    str(payload.get("profile") or "").strip(),
                    str(payload.get("slice_key") or "").strip(),
                    str(payload.get("status") or "").strip(),
                    json.dumps(payload),
                ),
            )
    return payload


def upsert_agent_identity(root_dir: str | Path | None, payload: dict[str, Any]) -> dict[str, Any]:
    root = repo_root(root_dir)
    agent_slug = str(payload.get("agent_slug") or payload.get("slug") or "").strip().lower()
    if not agent_slug:
        raise ValueError("agent identity requires agent_slug")

    if not using_postgres(root):
        graph = _load_memory_graph_file(root)
        graph["agents"][agent_slug] = payload
        _save_memory_graph_file(root, graph)
        return payload

    ensure_postgres_ready(root)
    with _connect(root) as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO hermes_agents (agent_slug, profile_key, lane, character_name, payload, updated_at)
                VALUES (%s, %s, %s, %s, %s::jsonb, NOW())
                ON CONFLICT (agent_slug) DO UPDATE
                SET profile_key = EXCLUDED.profile_key,
                    lane = EXCLUDED.lane,
                    character_name = EXCLUDED.character_name,
                    payload = EXCLUDED.payload,
                    updated_at = NOW()
                """,
                (
                    agent_slug,
                    str(payload.get("profile_key") or "").strip(),
                    str(payload.get("lane") or "").strip(),
                    str(payload.get("character_name") or agent_slug).strip(),
                    json.dumps(payload),
                ),
            )
    return payload


def upsert_memory_node(root_dir: str | Path | None, payload: dict[str, Any]) -> dict[str, Any]:
    root = repo_root(root_dir)
    node_id = str(payload.get("node_id") or "").strip()
    if not node_id:
        raise ValueError("memory node requires node_id")

    if not using_postgres(root):
        graph = _load_memory_graph_file(root)
        graph["nodes"][node_id] = payload
        _save_memory_graph_file(root, graph)
        return payload

    ensure_postgres_ready(root)
    with _connect(root) as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO hermes_memory_nodes (
                    node_id, agent_slug, scope, kind, title, content, source_path,
                    confidence, weight, payload, updated_at
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s::jsonb, NOW())
                ON CONFLICT (node_id) DO UPDATE
                SET agent_slug = EXCLUDED.agent_slug,
                    scope = EXCLUDED.scope,
                    kind = EXCLUDED.kind,
                    title = EXCLUDED.title,
                    content = EXCLUDED.content,
                    source_path = EXCLUDED.source_path,
                    confidence = EXCLUDED.confidence,
                    weight = EXCLUDED.weight,
                    payload = EXCLUDED.payload,
                    updated_at = NOW()
                """,
                (
                    node_id,
                    str(payload.get("agent_slug") or "").strip().lower(),
                    str(payload.get("scope") or "").strip(),
                    str(payload.get("kind") or "").strip(),
                    str(payload.get("title") or "").strip(),
                    str(payload.get("content") or "").strip(),
                    str(payload.get("source_path") or "").strip(),
                    float(payload.get("confidence") or 1.0),
                    float(payload.get("weight") or 1.0),
                    json.dumps(payload.get("payload") if isinstance(payload.get("payload"), dict) else {}),
                ),
            )
    return payload


def upsert_memory_synapse(root_dir: str | Path | None, payload: dict[str, Any]) -> dict[str, Any]:
    root = repo_root(root_dir)
    edge_id = str(payload.get("edge_id") or "").strip()
    if not edge_id:
        raise ValueError("memory synapse requires edge_id")

    if not using_postgres(root):
        graph = _load_memory_graph_file(root)
        graph["synapses"][edge_id] = payload
        _save_memory_graph_file(root, graph)
        return payload

    ensure_postgres_ready(root)
    with _connect(root) as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO hermes_memory_synapses (
                    edge_id, agent_slug, from_node_id, to_node_id, relation,
                    weight, payload, updated_at
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s::jsonb, NOW())
                ON CONFLICT (edge_id) DO UPDATE
                SET agent_slug = EXCLUDED.agent_slug,
                    from_node_id = EXCLUDED.from_node_id,
                    to_node_id = EXCLUDED.to_node_id,
                    relation = EXCLUDED.relation,
                    weight = EXCLUDED.weight,
                    payload = EXCLUDED.payload,
                    updated_at = NOW()
                """,
                (
                    edge_id,
                    str(payload.get("agent_slug") or "").strip().lower(),
                    str(payload.get("from_node_id") or "").strip(),
                    str(payload.get("to_node_id") or "").strip(),
                    str(payload.get("relation") or "").strip(),
                    float(payload.get("weight") or 1.0),
                    json.dumps(payload.get("payload") if isinstance(payload.get("payload"), dict) else {}),
                ),
            )
    return payload


def list_agent_identities(root_dir: str | Path | None = None) -> list[dict[str, Any]]:
    root = repo_root(root_dir)
    if not using_postgres(root):
        graph = _load_memory_graph_file(root)
        return [row for row in graph["agents"].values() if isinstance(row, dict)]

    ensure_postgres_ready(root)
    with _connect(root) as conn:
        with conn.cursor() as cur:
            cur.execute("SELECT payload FROM hermes_agents ORDER BY agent_slug")
            return [_load_json_value(row[0]) for row in cur.fetchall()]


def list_memory_nodes(root_dir: str | Path | None = None, *, agent_slug: str = "") -> list[dict[str, Any]]:
    root = repo_root(root_dir)
    normalized_slug = str(agent_slug or "").strip().lower()
    if not using_postgres(root):
        graph = _load_memory_graph_file(root)
        rows = [row for row in graph["nodes"].values() if isinstance(row, dict)]
        if normalized_slug:
            rows = [row for row in rows if str(row.get("agent_slug") or "").strip().lower() == normalized_slug]
        rows.sort(key=lambda row: (str(row.get("agent_slug") or ""), str(row.get("kind") or ""), str(row.get("title") or "")))
        return rows

    ensure_postgres_ready(root)
    with _connect(root) as conn:
        with conn.cursor() as cur:
            if normalized_slug:
                cur.execute(
                    """
                    SELECT jsonb_build_object(
                        'node_id', node_id,
                        'agent_slug', agent_slug,
                        'scope', scope,
                        'kind', kind,
                        'title', title,
                        'content', content,
                        'source_path', source_path,
                        'confidence', confidence,
                        'weight', weight,
                        'payload', payload
                    )
                    FROM hermes_memory_nodes
                    WHERE agent_slug = %s
                    ORDER BY weight DESC, kind, title
                    """,
                    (normalized_slug,),
                )
            else:
                cur.execute(
                    """
                    SELECT jsonb_build_object(
                        'node_id', node_id,
                        'agent_slug', agent_slug,
                        'scope', scope,
                        'kind', kind,
                        'title', title,
                        'content', content,
                        'source_path', source_path,
                        'confidence', confidence,
                        'weight', weight,
                        'payload', payload
                    )
                    FROM hermes_memory_nodes
                    ORDER BY agent_slug, weight DESC, kind, title
                    """
                )
            return [_load_json_value(row[0]) for row in cur.fetchall()]


def list_memory_synapses(root_dir: str | Path | None = None, *, agent_slug: str = "") -> list[dict[str, Any]]:
    root = repo_root(root_dir)
    normalized_slug = str(agent_slug or "").strip().lower()
    if not using_postgres(root):
        graph = _load_memory_graph_file(root)
        rows = [row for row in graph["synapses"].values() if isinstance(row, dict)]
        if normalized_slug:
            rows = [row for row in rows if str(row.get("agent_slug") or "").strip().lower() == normalized_slug]
        rows.sort(key=lambda row: (str(row.get("agent_slug") or ""), str(row.get("relation") or ""), -float(row.get("weight") or 1.0)))
        return rows

    ensure_postgres_ready(root)
    with _connect(root) as conn:
        with conn.cursor() as cur:
            if normalized_slug:
                cur.execute(
                    """
                    SELECT jsonb_build_object(
                        'edge_id', edge_id,
                        'agent_slug', agent_slug,
                        'from_node_id', from_node_id,
                        'to_node_id', to_node_id,
                        'relation', relation,
                        'weight', weight,
                        'payload', payload
                    )
                    FROM hermes_memory_synapses
                    WHERE agent_slug = %s
                    ORDER BY weight DESC, relation, edge_id
                    """,
                    (normalized_slug,),
                )
            else:
                cur.execute(
                    """
                    SELECT jsonb_build_object(
                        'edge_id', edge_id,
                        'agent_slug', agent_slug,
                        'from_node_id', from_node_id,
                        'to_node_id', to_node_id,
                        'relation', relation,
                        'weight', weight,
                        'payload', payload
                    )
                    FROM hermes_memory_synapses
                    ORDER BY agent_slug, weight DESC, relation, edge_id
                    """
                )
            return [_load_json_value(row[0]) for row in cur.fetchall()]


COGNITIVE_TABLES: dict[str, dict[str, str]] = {
    "events": {"table": "hermes_cognitive_events", "id": "event_id", "order": "occurred_at DESC, created_at DESC"},
    "facts": {"table": "hermes_cognitive_facts", "id": "fact_id", "order": "updated_at DESC"},
    "procedures": {"table": "hermes_cognitive_procedures", "id": "procedure_id", "order": "updated_at DESC"},
    "reflections": {"table": "hermes_cognitive_reflections", "id": "reflection_id", "order": "created_at DESC"},
    "activations": {"table": "hermes_cognitive_activations", "id": "activation_id", "order": "created_at DESC"},
    "beliefs": {"table": "hermes_agent_beliefs", "id": "belief_id", "order": "updated_at DESC"},
    "contradictions": {"table": "hermes_cognitive_contradictions", "id": "contradiction_id", "order": "updated_at DESC"},
    "dream_jobs": {"table": "hermes_dream_jobs", "id": "job_id", "order": "updated_at DESC"},
    "council_records": {"table": "hermes_council_records", "id": "council_id", "order": "created_at DESC"},
    "experiments": {"table": "hermes_experiments", "id": "experiment_id", "order": "updated_at DESC"},
    "skill_evolutions": {"table": "hermes_skill_evolutions", "id": "evolution_id", "order": "updated_at DESC"},
    "autonomy_decisions": {"table": "hermes_autonomy_decisions", "id": "decision_id", "order": "updated_at DESC"},
    "agent_heartbeats": {"table": "hermes_agent_heartbeats", "id": "heartbeat_id", "order": "updated_at DESC"},
    "agent_intentions": {"table": "hermes_agent_intentions", "id": "intention_id", "order": "updated_at DESC"},
}


def _cognitive_json_expr(kind: str) -> str:
    if kind == "events":
        return """
            jsonb_build_object(
                'event_id', event_id,
                'agent_slug', agent_slug,
                'project_id', project_id,
                'event_type', event_type,
                'title', title,
                'content', content,
                'source_ref', source_ref,
                'salience', salience,
                'payload', payload,
                'occurred_at', occurred_at::text
            )
        """
    if kind == "facts":
        return """
            jsonb_build_object(
                'fact_id', fact_id,
                'scope', scope,
                'subject', subject,
                'predicate', predicate,
                'object', object,
                'confidence', confidence,
                'source_event_id', source_event_id,
                'payload', payload
            )
        """
    if kind == "procedures":
        return """
            jsonb_build_object(
                'procedure_id', procedure_id,
                'agent_slug', agent_slug,
                'trigger', trigger,
                'title', title,
                'steps', steps,
                'confidence', confidence,
                'payload', payload
            )
        """
    if kind == "reflections":
        return """
            jsonb_build_object(
                'reflection_id', reflection_id,
                'agent_slug', agent_slug,
                'project_id', project_id,
                'title', title,
                'content', content,
                'lessons', lessons,
                'payload', payload,
                'created_at', created_at::text
            )
        """
    if kind == "activations":
        return """
            jsonb_build_object(
                'activation_id', activation_id,
                'query', query,
                'agent_slug', agent_slug,
                'project_id', project_id,
                'activated_nodes', activated_nodes,
                'activated_facts', activated_facts,
                'activated_procedures', activated_procedures,
                'chosen_action', chosen_action,
                'confidence', confidence,
                'payload', payload,
                'created_at', created_at::text
            )
        """
    if kind == "beliefs":
        return """
            jsonb_build_object(
                'belief_id', belief_id,
                'agent_slug', agent_slug,
                'subject', subject,
                'belief', belief,
                'confidence', confidence,
                'payload', payload
            )
        """
    if kind == "contradictions":
        return """
            jsonb_build_object(
                'contradiction_id', contradiction_id,
                'scope', scope,
                'subject', subject,
                'statement_a', statement_a,
                'statement_b', statement_b,
                'status', status,
                'severity', severity,
                'payload', payload
            )
        """
    if kind == "dream_jobs":
        return """
            jsonb_build_object(
                'job_id', job_id,
                'agent_slug', agent_slug,
                'job_type', job_type,
                'status', status,
                'objective', objective,
                'result', result,
                'created_at', created_at::text,
                'updated_at', updated_at::text
            )
        """
    if kind == "council_records":
        return """
            jsonb_build_object(
                'council_id', council_id,
                'project_id', project_id,
                'topic', topic,
                'positions', positions,
                'decision', decision,
                'confidence', confidence,
                'payload', payload,
                'created_at', created_at::text
            )
        """
    if kind == "experiments":
        return """
            jsonb_build_object(
                'experiment_id', experiment_id,
                'project_id', project_id,
                'hypothesis', hypothesis,
                'metric', metric,
                'status', status,
                'risk', risk,
                'confidence', confidence,
                'result', result,
                'payload', payload,
                'created_at', created_at::text,
                'updated_at', updated_at::text
            )
        """
    if kind == "skill_evolutions":
        return """
            jsonb_build_object(
                'evolution_id', evolution_id,
                'agent_slug', agent_slug,
                'skill_area', skill_area,
                'evidence', evidence,
                'recommendation', recommendation,
                'confidence', confidence,
                'payload', payload,
                'created_at', created_at::text,
                'updated_at', updated_at::text
            )
        """
    if kind == "autonomy_decisions":
        return """
            jsonb_build_object(
                'decision_id', decision_id,
                'project_id', project_id,
                'objective', objective,
                'risk', risk,
                'confidence', confidence,
                'decision', decision,
                'reasons', reasons,
                'payload', payload,
                'created_at', created_at::text,
                'updated_at', updated_at::text
            )
        """
    if kind == "agent_heartbeats":
        return """
            jsonb_build_object(
                'heartbeat_id', heartbeat_id,
                'agent_slug', agent_slug,
                'project_id', project_id,
                'status', status,
                'observation', observation,
                'intention', intention,
                'confidence', confidence,
                'payload', payload,
                'created_at', created_at::text,
                'updated_at', updated_at::text
            )
        """
    if kind == "agent_intentions":
        return """
            jsonb_build_object(
                'intention_id', intention_id,
                'agent_slug', agent_slug,
                'project_id', project_id,
                'title', title,
                'action_type', action_type,
                'status', status,
                'risk', risk,
                'confidence', confidence,
                'autonomy_decision', autonomy_decision,
                'payload', payload,
                'created_at', created_at::text,
                'updated_at', updated_at::text
            )
        """
    raise ValueError(f"Unknown cognitive record kind: {kind}")


def upsert_cognitive_record(root_dir: str | Path | None, kind: str, payload: dict[str, Any]) -> dict[str, Any]:
    root = repo_root(root_dir)
    config = COGNITIVE_TABLES.get(kind)
    if config is None:
        raise ValueError(f"Unknown cognitive record kind: {kind}")
    id_key = config["id"]
    record_id = str(payload.get(id_key) or "").strip()
    if not record_id:
        raise ValueError(f"{kind} record requires {id_key}")

    if not using_postgres(root):
        graph = _load_cognition_file(root)
        graph[kind][record_id] = payload
        _save_cognition_file(root, graph)
        return payload

    ensure_postgres_ready(root)
    with _connect(root) as conn:
        with conn.cursor() as cur:
            if kind == "events":
                cur.execute(
                    """
                    INSERT INTO hermes_cognitive_events (
                        event_id, agent_slug, project_id, event_type, title, content,
                        source_ref, salience, payload, occurred_at
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s::jsonb, COALESCE(%s::timestamptz, NOW()))
                    ON CONFLICT (event_id) DO UPDATE
                    SET agent_slug = EXCLUDED.agent_slug,
                        project_id = EXCLUDED.project_id,
                        event_type = EXCLUDED.event_type,
                        title = EXCLUDED.title,
                        content = EXCLUDED.content,
                        source_ref = EXCLUDED.source_ref,
                        salience = EXCLUDED.salience,
                        payload = EXCLUDED.payload,
                        occurred_at = EXCLUDED.occurred_at
                    """,
                    (
                        record_id,
                        str(payload.get("agent_slug") or "").strip(),
                        str(payload.get("project_id") or "").strip(),
                        str(payload.get("event_type") or "").strip(),
                        str(payload.get("title") or "").strip(),
                        str(payload.get("content") or "").strip(),
                        str(payload.get("source_ref") or "").strip(),
                        float(payload.get("salience") or 0.5),
                        json.dumps(payload.get("payload") if isinstance(payload.get("payload"), dict) else {}),
                        str(payload.get("occurred_at") or "").strip() or None,
                    ),
                )
            elif kind == "facts":
                cur.execute(
                    """
                    INSERT INTO hermes_cognitive_facts (
                        fact_id, scope, subject, predicate, object, confidence,
                        source_event_id, payload, updated_at
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s::jsonb, NOW())
                    ON CONFLICT (fact_id) DO UPDATE
                    SET scope = EXCLUDED.scope,
                        subject = EXCLUDED.subject,
                        predicate = EXCLUDED.predicate,
                        object = EXCLUDED.object,
                        confidence = EXCLUDED.confidence,
                        source_event_id = EXCLUDED.source_event_id,
                        payload = EXCLUDED.payload,
                        updated_at = NOW()
                    """,
                    (
                        record_id,
                        str(payload.get("scope") or "").strip(),
                        str(payload.get("subject") or "").strip(),
                        str(payload.get("predicate") or "").strip(),
                        str(payload.get("object") or "").strip(),
                        float(payload.get("confidence") or 0.75),
                        str(payload.get("source_event_id") or "").strip(),
                        json.dumps(payload.get("payload") if isinstance(payload.get("payload"), dict) else {}),
                    ),
                )
            elif kind == "procedures":
                cur.execute(
                    """
                    INSERT INTO hermes_cognitive_procedures (
                        procedure_id, agent_slug, trigger, title, steps, confidence,
                        payload, updated_at
                    )
                    VALUES (%s, %s, %s, %s, %s::jsonb, %s, %s::jsonb, NOW())
                    ON CONFLICT (procedure_id) DO UPDATE
                    SET agent_slug = EXCLUDED.agent_slug,
                        trigger = EXCLUDED.trigger,
                        title = EXCLUDED.title,
                        steps = EXCLUDED.steps,
                        confidence = EXCLUDED.confidence,
                        payload = EXCLUDED.payload,
                        updated_at = NOW()
                    """,
                    (
                        record_id,
                        str(payload.get("agent_slug") or "").strip(),
                        str(payload.get("trigger") or "").strip(),
                        str(payload.get("title") or "").strip(),
                        json.dumps(payload.get("steps") if isinstance(payload.get("steps"), list) else []),
                        float(payload.get("confidence") or 0.75),
                        json.dumps(payload.get("payload") if isinstance(payload.get("payload"), dict) else {}),
                    ),
                )
            elif kind == "reflections":
                cur.execute(
                    """
                    INSERT INTO hermes_cognitive_reflections (
                        reflection_id, agent_slug, project_id, title, content,
                        lessons, payload
                    )
                    VALUES (%s, %s, %s, %s, %s, %s::jsonb, %s::jsonb)
                    ON CONFLICT (reflection_id) DO UPDATE
                    SET agent_slug = EXCLUDED.agent_slug,
                        project_id = EXCLUDED.project_id,
                        title = EXCLUDED.title,
                        content = EXCLUDED.content,
                        lessons = EXCLUDED.lessons,
                        payload = EXCLUDED.payload
                    """,
                    (
                        record_id,
                        str(payload.get("agent_slug") or "").strip(),
                        str(payload.get("project_id") or "").strip(),
                        str(payload.get("title") or "").strip(),
                        str(payload.get("content") or "").strip(),
                        json.dumps(payload.get("lessons") if isinstance(payload.get("lessons"), list) else []),
                        json.dumps(payload.get("payload") if isinstance(payload.get("payload"), dict) else {}),
                    ),
                )
            elif kind == "activations":
                cur.execute(
                    """
                    INSERT INTO hermes_cognitive_activations (
                        activation_id, query, agent_slug, project_id, activated_nodes,
                        activated_facts, activated_procedures, chosen_action, confidence,
                        payload
                    )
                    VALUES (%s, %s, %s, %s, %s::jsonb, %s::jsonb, %s::jsonb, %s, %s, %s::jsonb)
                    ON CONFLICT (activation_id) DO UPDATE
                    SET query = EXCLUDED.query,
                        agent_slug = EXCLUDED.agent_slug,
                        project_id = EXCLUDED.project_id,
                        activated_nodes = EXCLUDED.activated_nodes,
                        activated_facts = EXCLUDED.activated_facts,
                        activated_procedures = EXCLUDED.activated_procedures,
                        chosen_action = EXCLUDED.chosen_action,
                        confidence = EXCLUDED.confidence,
                        payload = EXCLUDED.payload
                    """,
                    (
                        record_id,
                        str(payload.get("query") or "").strip(),
                        str(payload.get("agent_slug") or "").strip(),
                        str(payload.get("project_id") or "").strip(),
                        json.dumps(payload.get("activated_nodes") if isinstance(payload.get("activated_nodes"), list) else []),
                        json.dumps(payload.get("activated_facts") if isinstance(payload.get("activated_facts"), list) else []),
                        json.dumps(payload.get("activated_procedures") if isinstance(payload.get("activated_procedures"), list) else []),
                        str(payload.get("chosen_action") or "").strip(),
                        float(payload.get("confidence") or 0.0),
                        json.dumps(payload.get("payload") if isinstance(payload.get("payload"), dict) else {}),
                    ),
                )
            elif kind == "beliefs":
                cur.execute(
                    """
                    INSERT INTO hermes_agent_beliefs (
                        belief_id, agent_slug, subject, belief, confidence, payload,
                        updated_at
                    )
                    VALUES (%s, %s, %s, %s, %s, %s::jsonb, NOW())
                    ON CONFLICT (belief_id) DO UPDATE
                    SET agent_slug = EXCLUDED.agent_slug,
                        subject = EXCLUDED.subject,
                        belief = EXCLUDED.belief,
                        confidence = EXCLUDED.confidence,
                        payload = EXCLUDED.payload,
                        updated_at = NOW()
                    """,
                    (
                        record_id,
                        str(payload.get("agent_slug") or "").strip(),
                        str(payload.get("subject") or "").strip(),
                        str(payload.get("belief") or "").strip(),
                        float(payload.get("confidence") or 0.75),
                        json.dumps(payload.get("payload") if isinstance(payload.get("payload"), dict) else {}),
                    ),
                )
            elif kind == "contradictions":
                cur.execute(
                    """
                    INSERT INTO hermes_cognitive_contradictions (
                        contradiction_id, scope, subject, statement_a, statement_b,
                        status, severity, payload, updated_at
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s::jsonb, NOW())
                    ON CONFLICT (contradiction_id) DO UPDATE
                    SET scope = EXCLUDED.scope,
                        subject = EXCLUDED.subject,
                        statement_a = EXCLUDED.statement_a,
                        statement_b = EXCLUDED.statement_b,
                        status = EXCLUDED.status,
                        severity = EXCLUDED.severity,
                        payload = EXCLUDED.payload,
                        updated_at = NOW()
                    """,
                    (
                        record_id,
                        str(payload.get("scope") or "").strip(),
                        str(payload.get("subject") or "").strip(),
                        str(payload.get("statement_a") or "").strip(),
                        str(payload.get("statement_b") or "").strip(),
                        str(payload.get("status") or "open").strip(),
                        float(payload.get("severity") or 0.5),
                        json.dumps(payload.get("payload") if isinstance(payload.get("payload"), dict) else {}),
                    ),
                )
            elif kind == "dream_jobs":
                cur.execute(
                    """
                    INSERT INTO hermes_dream_jobs (
                        job_id, agent_slug, job_type, status, objective, result,
                        updated_at
                    )
                    VALUES (%s, %s, %s, %s, %s, %s::jsonb, NOW())
                    ON CONFLICT (job_id) DO UPDATE
                    SET agent_slug = EXCLUDED.agent_slug,
                        job_type = EXCLUDED.job_type,
                        status = EXCLUDED.status,
                        objective = EXCLUDED.objective,
                        result = EXCLUDED.result,
                        updated_at = NOW()
                    """,
                    (
                        record_id,
                        str(payload.get("agent_slug") or "").strip(),
                        str(payload.get("job_type") or "").strip(),
                        str(payload.get("status") or "queued").strip(),
                        str(payload.get("objective") or "").strip(),
                        json.dumps(payload.get("result") if isinstance(payload.get("result"), dict) else {}),
                    ),
                )
            elif kind == "council_records":
                cur.execute(
                    """
                    INSERT INTO hermes_council_records (
                        council_id, project_id, topic, positions, decision,
                        confidence, payload
                    )
                    VALUES (%s, %s, %s, %s::jsonb, %s, %s, %s::jsonb)
                    ON CONFLICT (council_id) DO UPDATE
                    SET project_id = EXCLUDED.project_id,
                        topic = EXCLUDED.topic,
                        positions = EXCLUDED.positions,
                        decision = EXCLUDED.decision,
                        confidence = EXCLUDED.confidence,
                        payload = EXCLUDED.payload
                    """,
                    (
                        record_id,
                        str(payload.get("project_id") or "").strip(),
                        str(payload.get("topic") or "").strip(),
                        json.dumps(payload.get("positions") if isinstance(payload.get("positions"), list) else []),
                        str(payload.get("decision") or "").strip(),
                        float(payload.get("confidence") or 0.0),
                        json.dumps(payload.get("payload") if isinstance(payload.get("payload"), dict) else {}),
                    ),
                )
            elif kind == "experiments":
                cur.execute(
                    """
                    INSERT INTO hermes_experiments (
                        experiment_id, project_id, hypothesis, metric, status, risk,
                        confidence, result, payload, updated_at
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s::jsonb, %s::jsonb, NOW())
                    ON CONFLICT (experiment_id) DO UPDATE
                    SET project_id = EXCLUDED.project_id,
                        hypothesis = EXCLUDED.hypothesis,
                        metric = EXCLUDED.metric,
                        status = EXCLUDED.status,
                        risk = EXCLUDED.risk,
                        confidence = EXCLUDED.confidence,
                        result = EXCLUDED.result,
                        payload = EXCLUDED.payload,
                        updated_at = NOW()
                    """,
                    (
                        record_id,
                        str(payload.get("project_id") or "").strip(),
                        str(payload.get("hypothesis") or "").strip(),
                        str(payload.get("metric") or "").strip(),
                        str(payload.get("status") or "proposed").strip(),
                        str(payload.get("risk") or "medium").strip(),
                        float(payload.get("confidence") or 0.0),
                        json.dumps(payload.get("result") if isinstance(payload.get("result"), dict) else {}),
                        json.dumps(payload.get("payload") if isinstance(payload.get("payload"), dict) else {}),
                    ),
                )
            elif kind == "skill_evolutions":
                cur.execute(
                    """
                    INSERT INTO hermes_skill_evolutions (
                        evolution_id, agent_slug, skill_area, evidence,
                        recommendation, confidence, payload, updated_at
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, %s::jsonb, NOW())
                    ON CONFLICT (evolution_id) DO UPDATE
                    SET agent_slug = EXCLUDED.agent_slug,
                        skill_area = EXCLUDED.skill_area,
                        evidence = EXCLUDED.evidence,
                        recommendation = EXCLUDED.recommendation,
                        confidence = EXCLUDED.confidence,
                        payload = EXCLUDED.payload,
                        updated_at = NOW()
                    """,
                    (
                        record_id,
                        str(payload.get("agent_slug") or "").strip(),
                        str(payload.get("skill_area") or "").strip(),
                        str(payload.get("evidence") or "").strip(),
                        str(payload.get("recommendation") or "").strip(),
                        float(payload.get("confidence") or 0.0),
                        json.dumps(payload.get("payload") if isinstance(payload.get("payload"), dict) else {}),
                    ),
                )
            elif kind == "autonomy_decisions":
                cur.execute(
                    """
                    INSERT INTO hermes_autonomy_decisions (
                        decision_id, project_id, objective, risk, confidence,
                        decision, reasons, payload, updated_at
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, %s::jsonb, %s::jsonb, NOW())
                    ON CONFLICT (decision_id) DO UPDATE
                    SET project_id = EXCLUDED.project_id,
                        objective = EXCLUDED.objective,
                        risk = EXCLUDED.risk,
                        confidence = EXCLUDED.confidence,
                        decision = EXCLUDED.decision,
                        reasons = EXCLUDED.reasons,
                        payload = EXCLUDED.payload,
                        updated_at = NOW()
                    """,
                    (
                        record_id,
                        str(payload.get("project_id") or "").strip(),
                        str(payload.get("objective") or "").strip(),
                        str(payload.get("risk") or "medium").strip(),
                        float(payload.get("confidence") or 0.0),
                        str(payload.get("decision") or "").strip(),
                        json.dumps(payload.get("reasons") if isinstance(payload.get("reasons"), list) else []),
                        json.dumps(payload.get("payload") if isinstance(payload.get("payload"), dict) else {}),
                    ),
                )
            elif kind == "agent_heartbeats":
                cur.execute(
                    """
                    INSERT INTO hermes_agent_heartbeats (
                        heartbeat_id, agent_slug, project_id, status, observation,
                        intention, confidence, payload, updated_at
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s::jsonb, NOW())
                    ON CONFLICT (heartbeat_id) DO UPDATE
                    SET agent_slug = EXCLUDED.agent_slug,
                        project_id = EXCLUDED.project_id,
                        status = EXCLUDED.status,
                        observation = EXCLUDED.observation,
                        intention = EXCLUDED.intention,
                        confidence = EXCLUDED.confidence,
                        payload = EXCLUDED.payload,
                        updated_at = NOW()
                    """,
                    (
                        record_id,
                        str(payload.get("agent_slug") or "").strip(),
                        str(payload.get("project_id") or "").strip(),
                        str(payload.get("status") or "listening").strip(),
                        str(payload.get("observation") or "").strip(),
                        str(payload.get("intention") or "").strip(),
                        float(payload.get("confidence") or 0.0),
                        json.dumps(payload.get("payload") if isinstance(payload.get("payload"), dict) else {}),
                    ),
                )
            elif kind == "agent_intentions":
                cur.execute(
                    """
                    INSERT INTO hermes_agent_intentions (
                        intention_id, agent_slug, project_id, title, action_type,
                        status, risk, confidence, autonomy_decision, payload,
                        updated_at
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s::jsonb, NOW())
                    ON CONFLICT (intention_id) DO UPDATE
                    SET agent_slug = EXCLUDED.agent_slug,
                        project_id = EXCLUDED.project_id,
                        title = EXCLUDED.title,
                        action_type = EXCLUDED.action_type,
                        status = EXCLUDED.status,
                        risk = EXCLUDED.risk,
                        confidence = EXCLUDED.confidence,
                        autonomy_decision = EXCLUDED.autonomy_decision,
                        payload = EXCLUDED.payload,
                        updated_at = NOW()
                    """,
                    (
                        record_id,
                        str(payload.get("agent_slug") or "").strip(),
                        str(payload.get("project_id") or "").strip(),
                        str(payload.get("title") or "").strip(),
                        str(payload.get("action_type") or "").strip(),
                        str(payload.get("status") or "proposed").strip(),
                        str(payload.get("risk") or "low").strip(),
                        float(payload.get("confidence") or 0.0),
                        str(payload.get("autonomy_decision") or "").strip(),
                        json.dumps(payload.get("payload") if isinstance(payload.get("payload"), dict) else {}),
                    ),
                )
    return payload


def list_cognitive_records(
    root_dir: str | Path | None = None,
    kind: str = "events",
    *,
    agent_slug: str = "",
    limit: int = 50,
) -> list[dict[str, Any]]:
    root = repo_root(root_dir)
    config = COGNITIVE_TABLES.get(kind)
    if config is None:
        raise ValueError(f"Unknown cognitive record kind: {kind}")
    normalized_slug = str(agent_slug or "").strip().lower()
    if not using_postgres(root):
        graph = _load_cognition_file(root)
        rows = [row for row in graph[kind].values() if isinstance(row, dict)]
        if normalized_slug:
            rows = [row for row in rows if str(row.get("agent_slug") or "").strip().lower() == normalized_slug]
        return rows[: max(1, limit)]

    ensure_postgres_ready(root)
    table = config["table"]
    order = config["order"]
    expr = _cognitive_json_expr(kind)
    with _connect(root) as conn:
        with conn.cursor() as cur:
            if normalized_slug and kind in {"events", "procedures", "reflections", "activations", "beliefs", "dream_jobs", "skill_evolutions", "agent_heartbeats", "agent_intentions"}:
                cur.execute(
                    f"""
                    SELECT {expr}
                    FROM {table}
                    WHERE agent_slug = %s
                    ORDER BY {order}
                    LIMIT %s
                    """,
                    (normalized_slug, max(1, limit)),
                )
            else:
                cur.execute(
                    f"""
                    SELECT {expr}
                    FROM {table}
                    ORDER BY {order}
                    LIMIT %s
                    """,
                    (max(1, limit),),
                )
            return [_load_json_value(row[0]) for row in cur.fetchall()]
