# Bare-metal Nginx site for the Maze game
server {
  listen 80;
  listen [::]:80;
  # CHANGE THIS to your domain or the server's public IP
  server_name example.com www.example.com;

  root /var/www/maze-forest;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }
}
